---
- name: Install Slurm build dependencies
  yum:
    name:
      - rpm-build
      - gcc
      - gcc-c++
      - make
      - munge-devel
      - pam-devel
      - numactl-devel
      - readline-devel
      - openssl-devel
      - perl-ExtUtils-MakeMaker
    state: present

- name: Create RPM build tree
  shell: |
    mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

- name: Copy slurm tarball
  copy:
    src: slurm-24.11.5.tar.bz2
    dest: ~/rpmbuild/SOURCES/

- name: Build RPM from tarball
  shell: |
    cd ~/rpmbuild/SOURCES
    rpmbuild -ta slurm-24.11.5.tar.bz2
  args:
    creates: ~/rpmbuild/RPMS

- name: Install built Slurm RPMs
  shell: |
    yum -y localinstall ~/rpmbuild/RPMS/x86_64/*.rpm

- name: Create slurm config directory
  file:
    path: /usr/local/etc/slurm
    state: directory

- name: Render slurm.conf
  template:
    src: slurm.conf.j2
    dest: /usr/local/etc/slurm/slurm.conf

- name: Enable and start slurmctld on controller
  systemd:
    name: slurmctld
    enabled: true
    state: started
  when: inventory_hostname == groups['slurm_controller'][0]

- name: Enable and start slurmd on all nodes
  systemd:
    name: slurmd
    enabled: true
    state: started

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted
