- name: Create slurm group if not exists
  group:
    name: "{{ slurm_group }}"
    state: present

- name: Ensure slurm user exists
  user:
    name: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    createhome: no
    system: yes

- name: Create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0755'
  loop: "{{ slurm_dirs }}"

- name: Upload Slurm RPM packages
  copy:
    src: "{{ item }}"
    dest: "{{ slurm_rpm_dest_dir }}/"
    mode: '0644'
  loop: "{{ lookup('fileglob', 'files/' + slurm_rpm_src_dir + '/*.rpm', wantlist=True) }}"

- name: Install Slurm RPM packages
  yum:
    name: "{{ slurm_rpm_dest_dir }}/{{ item | basename }}"
    state: present
  loop: "{{ lookup('fileglob', 'files/' + slurm_rpm_src_dir + '/*.rpm', wantlist=True) | map('basename') | list }}"

- name: Render slurm.conf from template
  template:
    src: slurm.conf.j2
    dest: "{{ slurm_conf_path }}"
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0644'

- name: Enable and start slurmctld on controller node
  systemd:
    name: slurmctld
    enabled: yes
    state: started
  when: inventory_hostname == groups['slurm_controller'][0]

- name: Enable and start slurmd on all nodes
  systemd:
    name: slurmd
    enabled: yes
    state: started
