---
# - name: Install required packages (Debian)
#   apt:
#     name: 
#       - mariadb-server
#       - MySQL-python
#       - PyMySQL
#     state: present
#     update_cache: yes
#   when: 
#     - ansible_facts['os_family'] == "Debian"
#     - inventory_hostname == groups['slurm_controller'][0]

- name: Install required packages (RedHat)
  yum:
    name: 
      - mariadb-server
      - MySQL-python
      # - python3-pymysql
    state: present
  when: 
    - ansible_facts['os_family'] == "RedHat"
    - inventory_hostname == groups['slurm_controller'][0]



- name: Deploy my.cnf configuration
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    mode: '0644'
  notify: restart mariadb
  when:
    - inventory_hostname == groups['slurm_controller'][0]    

- name: Ensure MariaDB is started and enabled
  service:
    name: mariadb
    state: started
    enabled: yes
  when: 
    - ansible_facts['os_family'] == "RedHat"
    - inventory_hostname == groups['slurm_controller'][0]

# - name: Ensure MariaDB is started and enabled (Debian)
#   service:
#     name: mariadb
#     state: started
#     enabled: yes
#   when: 
#     - ansible_facts['os_family'] == "RedHat"
#     - inventory_hostname == groups['slurm_controller'][0]

- name: Set root password (for first time)
  mysql_user:
    name: root
    host_all: true
    password: "{{ slurm_db_pass }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
  ignore_errors: yes
  when:
    - inventory_hostname == groups['slurm_controller'][0]

- name: Create database
  mysql_db:
    name: "{{ slurm_db_name }}"
    state: present
    login_user: root
    login_password: "{{ slurm_db_pass }}"
  when:
    - inventory_hostname == groups['slurm_controller'][0]


- name: Create slurm database user
  mysql_user:
    name: "{{ slurm_db_user }}"
    host: localhost
    password: "{{ slurm_db_pass }}"
    priv: "*.*:ALL"
    state: present
    login_user: root
    login_password: "{{ slurm_db_pass }}"
  when: 
    - inventory_hostname == groups['slurm_controller'][0]